---
type: llm
provider: litellm_llm
models:
# Amazon Bedrock Claude モデル設定
# 注意: 推論プロファイルを使用する場合は、AWS コンソールで作成した推論プロファイルの ID を使用してください

- alias: default
  model: bedrock/converse/us.anthropic.claude-sonnet-4-20250514-v1:0
  timeout: 600
  kwargs:
    n: 1
    temperature: 0
  aws_region_name: us-east-1

- model: bedrock/converse/us.anthropic.claude-3-7-sonnet-20250219-v1:0
  timeout: 600
  kwargs:
    n: 1
    temperature: 0
  aws_region_name: us-east-1

---
type: embedder
provider: litellm_embedder
models:
  - alias: default
    model: bedrock/amazon.titan-embed-text-v2:0
    timeout: 600
    aws_region_name: us-east-1

---
type: engine
provider: wren_ui
endpoint: http://wren-ui:3000/absproxy/3000

---
type: engine
provider: wren_ibis
endpoint: http://ibis-server:8000

---
type: document_store
provider: qdrant
location: http://qdrant:6333
embedding_model_dim: 1024
timeout: 120
recreate_index: true

---
type: pipeline
llm: litellm_llm.bedrock/converse/us.anthropic.claude-sonnet-4-20250514-v1:0
embedder: litellm_embedder.bedrock/amazon.titan-embed-text-v2:0
pipes:
  - name: db_schema_indexing
    embedder: litellm_embedder.default
    document_store: qdrant
  - name: historical_question_indexing
    embedder: litellm_embedder.default
    document_store: qdrant
  - name: table_description_indexing
    embedder: litellm_embedder.default
    document_store: qdrant
  - name: db_schema_retrieval
    llm: litellm_llm.default
    embedder: litellm_embedder.default
    document_store: qdrant
  - name: historical_question_retrieval
    embedder: litellm_embedder.default
    document_store: qdrant
  - name: sql_generation
    llm: litellm_llm.default
    engine: wren_ui
    document_store: qdrant
  - name: sql_correction
    llm: litellm_llm.default
    engine: wren_ui
    document_store: qdrant
  - name: followup_sql_generation
    llm: litellm_llm.default
    engine: wren_ui
    document_store: qdrant
  - name: sql_answer
    llm: litellm_llm.default
  - name: semantics_description
    llm: litellm_llm.default
  - name: relationship_recommendation
    llm: litellm_llm.default
    engine: wren_ui
  - name: question_recommendation
    llm: litellm_llm.default
  - name: question_recommendation_db_schema_retrieval
    llm: litellm_llm.default
    embedder: litellm_embedder.default
    document_store: qdrant
  - name: question_recommendation_sql_generation
    llm: litellm_llm.default
    engine: wren_ui
    document_store: qdrant
  - name: intent_classification
    llm: litellm_llm.default
    embedder: litellm_embedder.default
    document_store: qdrant
  - name: misleading_assistance
    llm: litellm_llm.default
  - name: data_assistance
    llm: litellm_llm.default
  - name: sql_pairs_indexing
    document_store: qdrant
    embedder: litellm_embedder.default
  - name: sql_pairs_retrieval
    document_store: qdrant
    embedder: litellm_embedder.default
    llm: litellm_llm.default
  - name: preprocess_sql_data
    llm: litellm_llm.default
  - name: sql_executor
    engine: wren_ui
  - name: chart_generation
    llm: litellm_llm.default
  - name: chart_adjustment
    llm: litellm_llm.default
  - name: user_guide_assistance
    llm: litellm_llm.default
  - name: sql_question_generation
    llm: litellm_llm.default
  - name: sql_generation_reasoning
    llm: litellm_llm.default
  - name: followup_sql_generation_reasoning
    llm: litellm_llm.default
  - name: sql_regeneration
    llm: litellm_llm.default
    engine: wren_ui
  - name: instructions_indexing
    embedder: litellm_embedder.default
    document_store: qdrant
  - name: instructions_retrieval
    embedder: litellm_embedder.default
    document_store: qdrant
  - name: sql_functions_retrieval
    engine: wren_ibis
    document_store: qdrant
  - name: project_meta_indexing
    document_store: qdrant
  - name: sql_tables_extraction
    llm: litellm_llm.default

---
settings:
  litellm_settings:
    fallbacks: [
      {"bedrock/converse/us.anthropic.claude-sonnet-4-20250514-v1:0": 
        [
          "bedrock/converse/us.anthropic.claude-3-7-sonnet-20250219-v1:0"
        ]
      }
    ]
    num_retries: 2
    request_timeout: 30
    aws_region_name: us-east-1
    aws_session_name: "litellm-bedrock-session"
    drop_params: true

  router_settings:
    default_model: bedrock/converse/us.anthropic.claude-sonnet-4-20250514-v1:0
    failover: true
    timeout: 30
    retries: 3
